"""Run real evalscope requests through a TCP reset injector.

Owns and supervises q4t so SIGPIPE is recorded as an exit signal. The proxy
only forwards HTTP/SSE; requests and recovery runs are generated by evalscope.
"""
import argparse
import asyncio
import base64
import hashlib
import json
import os
import pathlib
import pickle
import shutil
import signal
import socket
import sqlite3
import struct
import subprocess

ROOT = pathlib.Path(__file__).resolve().parents[2]
EVAL = ROOT / 'tools/evalscope/.venv/bin/evalscope'
MODEL = '/home/rm01/models/dev/llm/garnermccloud/Qwen3.8-Flash-Next-NVFP4-SSD-Stream'


async def main(args):
    out = args.out.resolve()
    if not any(out.is_relative_to(ROOT / name) for name in ('build', '.q4t-work')):
        raise ValueError('Results must be inside build/ or .q4t-work/')
    out.mkdir(parents=True, exist_ok=False)
    shutil.copyfile(__file__, out / 'disconnect_e2e.py')
    fixture = json.loads(args.fixture.read_text().splitlines()[0])
    fixture.update(max_tokens=64, stream=True, stream_options={'include_usage': True})
    (out / 'request.jsonl').write_text(json.dumps(fixture) + '\n')
    env = os.environ.copy()
    for key in list(env):
        if key.startswith(('Q4T_FP8', 'Q4T_PROFILE', 'Q4T_MTP_TIMING', 'Q4T_SCHED_DEBUG')):
            env.pop(key)
    env['Q4T_ACCESS_LOG'] = '1'
    command = [str(args.binary.resolve()), 'serve', '--port', str(args.port),
               '--max-seq', '1', '--max-prefill', '2048', '--max-len', '8192']
    (out / 'command.json').write_text(json.dumps(command, indent=2))
    (out / 'binary.sha256').write_text(hashlib.sha256(args.binary.read_bytes()).hexdigest())
    (out / 'worktree.patch').write_bytes(subprocess.check_output(['git', 'diff'], cwd=ROOT))
    server_log = (out / 'server.log').open('w')
    # Restore SIGPIPE to the usual executable default, rather than inheriting
    # Python's ignored disposition and inadvertently hiding the server defect.
    server = subprocess.Popen(command, env=env, stdout=server_log,
                              stderr=subprocess.STDOUT, restore_signals=True)
    events = []
    proxy = None
    mode = 0
    proxy_error = None

    async def inject(reader, writer):
        nonlocal proxy_error
        upstream = None
        try:
            head = await reader.readuntil(b'\r\n\r\n')
            length = next(int(line.split(b':', 1)[1]) for line in head.split(b'\r\n')
                          if line.lower().startswith(b'content-length:'))
            body = await reader.readexactly(length)
            upstream_reader, upstream = await asyncio.open_connection('127.0.0.1', args.port)
            upstream.write(head + body)
            await upstream.drain()
            emitted = 0
            if mode < 0:
                await asyncio.sleep(0.05)  # Let the complete request reach the server.
            if mode >= 0:
                response_head = await upstream_reader.readuntil(b'\r\n\r\n')
                writer.write(response_head)
                await writer.drain()
                while emitted < mode:
                    chunk = await upstream_reader.readuntil(b'\r\n\r\n')
                    writer.write(chunk)
                    await writer.drain()
                    data = chunk.removeprefix(b'data:').strip()
                    if data == b'[DONE]':
                        raise RuntimeError('Response finished before fault injection')
                    obj = json.loads(data)
                    if any(c.get('delta', {}).get('content') for c in obj.get('choices', [])):
                        emitted += 1
            upstream.get_extra_info('socket').setsockopt(
                socket.SOL_SOCKET, socket.SO_LINGER, struct.pack('ii', 1, 0))
            upstream.transport.abort()
            events.append({'mode': mode, 'content_chunks_before_reset': emitted,
                           'event': 'upstream_tcp_reset'})
        except Exception as exc:
            proxy_error = repr(exc)
        finally:
            if upstream is not None:
                upstream.close()
            writer.close()

    async def metrics_snapshot():
        # Read service counters as evidence within the E2E scenario. This does
        # not issue an additional inference request or run a component test.
        reader, writer = await asyncio.open_connection('127.0.0.1', args.port)
        writer.write(b'GET /metrics HTTP/1.1\r\nHost: localhost\r\nConnection: close\r\n\r\n')
        await writer.drain()
        response = await asyncio.wait_for(reader.read(), timeout=10)
        writer.close()
        await writer.wait_closed()
        text = response.decode()
        values = {}
        for line in text.splitlines():
            if line.startswith(('q4t_requests_aborted_total ', 'q4t_requests_success_total ')):
                key, value = line.split()
                values[key] = int(value)
        return values

    async def evaluate(label, port):
        directory = out / label
        directory.mkdir()
        command = [str(EVAL), 'perf', '--model', 'qwen3.8-flash-next',
                   '--url', f'http://127.0.0.1:{port}/v1/chat/completions',
                   '--api', 'openai', '--tokenizer-path', MODEL,
                   '--dataset', 'line_by_line', '--dataset-path', str(out / 'request.jsonl'),
                   '--no-apply-chat-template', '--max-tokens', '64', '--parallel', '1',
                   '--number', '1', '--no-test-connection', '--stream',
                   '--connect-timeout', '10', '--read-timeout', '60', '--total-timeout', '90',
                   '--outputs-dir', str(directory)]
        (directory / 'command.json').write_text(json.dumps(command, indent=2))
        with (directory / 'client.log').open('w') as log:
            client = await asyncio.create_subprocess_exec(*command, stdout=log,
                                                         stderr=asyncio.subprocess.STDOUT)
            try:
                return await asyncio.wait_for(client.wait(), timeout=120)
            except asyncio.TimeoutError:
                client.terminate()
                await client.wait()
                raise RuntimeError(f'{label}: evalscope timed out')

    try:
        for _ in range(180):
            if server.poll() is not None:
                raise RuntimeError(f'Server exited during startup: {server.returncode}')
            if 'serving on port' in (out / 'server.log').read_text():
                break
            await asyncio.sleep(1)
        else:
            raise RuntimeError('Server startup timed out')
        proxy = await asyncio.start_server(inject, '127.0.0.1', args.port + 1)
        reference_text = None
        for index in range(args.rounds):
            mode = (-1, 1, 8)[index % 3]  # upload, first content, mid-decode
            await evaluate(f'fault-{index}', args.port + 1)
            await asyncio.sleep(0.5)
            if proxy_error or len(events) != index + 1:
                raise RuntimeError(f'Fault injection failed: {proxy_error}')
            code = server.poll()
            events[-1]['server_returncode'] = code
            print(json.dumps(events[-1]), flush=True)
            if args.expect_sigpipe:
                if code != -signal.SIGPIPE:
                    raise RuntimeError(f'Expected SIGPIPE, observed {code}')
                return
            if code is not None:
                raise RuntimeError(f'Server died after reset: {code}')
            label = f'recovery-{index}'
            if await evaluate(label, args.port) != 0:
                raise RuntimeError('Recovery evalscope failed')
            db = next((out / label).rglob('benchmark_data.db'))
            with sqlite3.connect(f'file:{db}?mode=ro', uri=True) as connection:
                row = connection.execute(
                    'SELECT success, prompt_tokens, completion_tokens, response_messages '
                    'FROM result').fetchone()
            if row is None or row[:3] != (1, 1024, 64):
                raise RuntimeError(f'Recovery length/success mismatch: {row[:3] if row else None}')
            # Only deserialize the database just produced by our trusted local evalscope.
            responses = pickle.loads(base64.b64decode(row[3]))
            text = ''.join(c.get('delta', {}).get('content', '')
                           for r in responses for c in r.get('choices', []))
            if reference_text is None:
                reference_text = text
            if text != reference_text:
                raise RuntimeError('Recovery output changed after reset/slot reuse')
            counts = await metrics_snapshot()
            if counts.get('q4t_requests_aborted_total') != index + 1:
                raise RuntimeError(f'Abort count mismatch: {counts}')
            if counts.get('q4t_requests_success_total') != index + 1:
                raise RuntimeError(f'Aborted request counted as success: {counts}')
            events[-1]['metrics'] = counts
            events[-1]['recovery'] = 'passed'
            events[-1]['output_sha256'] = hashlib.sha256(text.encode()).hexdigest()
            events[-1]['server_fd_count'] = len(list(pathlib.Path(f'/proc/{server.pid}/fd').iterdir()))
            print(json.dumps(events[-1]), flush=True)
    finally:
        if proxy is not None:
            proxy.close()
            await proxy.wait_closed()
        natural_exit = server.poll()
        if natural_exit is None:
            server.terminate()
            try:
                await asyncio.wait_for(asyncio.to_thread(server.wait), timeout=25)
            except asyncio.TimeoutError:
                server.kill()
                await asyncio.to_thread(server.wait)
        (out / 'result.json').write_text(json.dumps({
            'events': events, 'exit_before_cleanup': natural_exit,
            'exit_after_cleanup': server.returncode, 'proxy_error': proxy_error}, indent=2))
        server_log.close()


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--out', type=pathlib.Path, required=True)
    parser.add_argument('--binary', type=pathlib.Path, default=ROOT / 'build/q4t')
    parser.add_argument('--fixture', type=pathlib.Path,
                        default=ROOT / '.q4t-work/e2e/20260920-baseline/context-1024/requests.jsonl')
    parser.add_argument('--port', type=int, default=18000)
    parser.add_argument('--rounds', type=int, default=6)
    parser.add_argument('--expect-sigpipe', action='store_true')
    asyncio.run(main(parser.parse_args()))
