// Tests for the PLE n-gram hash.
//
// The reference row IDs below were generated by running SGLang's exact
// `_hash_contexts` algorithm (with the real checkpoint multipliers / vocab /
// offsets) in Python. The C++ implementation must reproduce them bit-for-bit.
//
// Checkpoint source (0-indexed layer 1 PLE):
//   ~/models/dev/llm/garnermccloud/Qwen3.8-Flash-Next-NVFP4-SSD-Stream
//   model-bf16-00001.safetensors  (layer_multipliers)
//   model-bf16-00010.safetensors  (ngram_heads_vocab_sizes, ngram_heads_offsets)
//   model-plefp8-scale.safetensors (weight_scale)
#include "q4t/ple/ngram_hash.h"
#include "q4t/ple/ngram_hash_derive.h"
#include "q4t/test.h"

namespace {

using q4t::ple::ComputeNgramRowIds;
using q4t::ple::DeriveLayerMultipliers;
using q4t::ple::NgramHashParams;

// Real checkpoint values.
const int64_t kMultipliers[3] = {23703573157769LL, 20109073645365LL,
                                 8052911324071LL};
const int64_t kVocab[16] = {
    20000003, 20000023, 20000033, 20000047, 20000059, 20000063, 20000069,
    20000077, 20000081, 20000093, 20000107, 20000147, 20000153, 20000159,
    20000161, 20000171};
const int64_t kOffsets[16] = {
    0,          20000003, 40000026, 60000059, 80000106,  100000165,
    120000228,  140000297, 160000374, 180000455, 200000548, 220000655,
    240000802,  260000955, 280001114, 300001275};

NgramHashParams MakeParams() {
  NgramHashParams p;
  p.ngram_size = 3;
  p.heads_per_ngram = 8;
  p.multipliers.assign(kMultipliers, kMultipliers + 3);
  p.head_vocab_sizes.assign(kVocab, kVocab + 16);
  p.head_offsets.assign(kOffsets, kOffsets + 16);
  return p;
}

bool CheckWindow(const NgramHashParams& p, const int64_t* window,
                 const int64_t* expected) {
  int64_t out[16];
  ComputeNgramRowIds(p, window, 248044, out);
  for (int i = 0; i < 16; ++i) {
    if (out[i] != expected[i]) {
      std::printf("  head %d: got %lld want %lld\n", i,
                  (long long)out[i], (long long)expected[i]);
      return false;
    }
  }
  return true;
}

}  // namespace

Q4T_TEST(ple_ngram_hash_matches_sglang_reference) {
  auto p = MakeParams();
  const int64_t kEos = 248044;

  struct Case {
    int64_t window[3];
    int64_t expected[16];
  };
  const Case cases[] = {
      {{101, 205, 306},
       {19605724, 38387754, 47783709, 60943576, 92228657, 115991450,
        121636535, 149165232, 170795115, 198365910, 200537214, 232488083,
        256285041, 260082938, 294682746, 307682328}},
      {{kEos, 205, 306},
       {19605724, 38387754, 47783709, 60943576, 92228657, 115991450,
        121636535, 149165232, 167574244, 194458970, 200972989, 233213670,
        250426283, 267997966, 287268427, 304218538}},
      {{101, kEos, 306},
       {5856811, 26147621, 40029066, 63647451, 87777261, 116617614,
        130625259, 150696903, 177411172, 181032705, 208127523, 228063710,
        252757585, 278678418, 280924632, 314200783}},
      {{5, 6, 7},
       {9319853, 32980418, 54810932, 61373850, 95570932, 100303321,
        137402047, 146866965, 160487518, 192851935, 200610520, 228493582,
        254676383, 260859079, 296253588, 313224935}},
      {{248000, 248001, 248002},
       {3070182, 23718960, 55158262, 68421906, 92378818, 113935672,
        126493868, 150321043, 171350825, 192265147, 204321062, 236065419,
        248577226, 261284711, 292230904, 307286882}},
  };
  for (const auto& c : cases) {
    Q4T_CHECK(CheckWindow(p, c.window, c.expected));
  }
  return true;
}

Q4T_TEST(ple_ngram_hash_row_ids_in_table_range) {
  auto p = MakeParams();
  // Max possible row id = last offset + (last vocab - 1).
  const int64_t max_row = kOffsets[15] + (kVocab[15] - 1);
  Q4T_CHECK(max_row == 320001445);
  // The sidecar has 320001536 rows (padded to a multiple of 128); every
  // computed row id must be below the sidecar row count.
  const int64_t sidecar_rows = 320001536;
  Q4T_CHECK(max_row < sidecar_rows);

  int64_t out[16];
  // A few windows; verify all ids in [0, sidecar_rows).
  const int64_t windows[][3] = {{0, 0, 0}, {1, 2, 3}, {248044, 248044, 248044},
                                {248319, 248318, 248317}};
  for (const auto& w : windows) {
    ComputeNgramRowIds(p, w, 248044, out);
    for (int i = 0; i < 16; ++i) {
      Q4T_CHECK(out[i] >= 0 && out[i] < sidecar_rows);
    }
  }
  return true;
}

Q4T_TEST(ple_multipliers_derivation_matches_checkpoint) {
  // seed=1234, ple_layer_index=0, ngram_size=3, vocab=248320 must reproduce
  // the checkpoint multipliers exactly.
  auto derived = DeriveLayerMultipliers(1234, 0, 3, 248320);
  Q4T_CHECK(derived.size() == 3);
  Q4T_CHECK(derived[0] == kMultipliers[0]);
  Q4T_CHECK(derived[1] == kMultipliers[1]);
  Q4T_CHECK(derived[2] == kMultipliers[2]);
  return true;
}
