// Tests for the GPT-2 Byte-Level BPE tokenizer.
//
// Two layers of validation:
//   1. Golden cases generated by the reference `tokenizers` library
//      (0.23.2) against the real model's tokenizer.json. These pin exact
//      token ids for ASCII, CJK, accented, emoji, whitespace, and
//      contraction inputs.
//   2. Load + round-trip against the real model's tokenizer.json.
#include "q4t/text/tokenizer.h"
#include "q4t/test.h"

#include <cstdio>
#include <fcntl.h>
#include <string>
#include <unistd.h>
#include <vector>

namespace {

using q4t::text::Tokenizer;
using q4t::text::TokenizerLimits;

const char* kRealTokenizer =
    "/home/rm01/models/dev/llm/garnermccloud/Qwen3.8-Flash-Next-NVFP4-SSD-Stream/"
    "tokenizer.json";

bool FileExists(const char* path) {
  int fd = open(path, O_RDONLY);
  if (fd < 0) return false;
  close(fd);
  return true;
}

struct GoldenCase {
  const char* text;
  std::vector<std::uint32_t> ids;
};

// Golden encode cases from `tokenizers` 0.23.2 on the real tokenizer.json.
const GoldenCase kGoldenCases[] = {
    {"Hello, world!", {9419, 11, 1814, 0}},
    {"\xe4\xbd\xa0\xe5\xa5\xbd\xef\xbc\x8c\xe4\xb8\x96\xe7\x95\x8c\xef\xbc\x81",
     {109266, 3709, 96748, 6115}},  // 你好，世界！
    {"The quick brown fox jumps over the lazy dog.",
     {760, 3841, 13477, 37550, 33075, 888, 279, 15217, 5388, 13}},
    {"Qwen3.8-Flash-Next runs on Jetson AGX Thor (SM110a).",
     {48, 16451, 18, 13, 23, 12, 23129, 12, 5666, 8213, 383, 23597, 901, 14642,
      55, 27520, 318, 9221, 16, 16, 15, 64, 553}},
    {"PLE SSD Stream: 51.2 GB FP8 lookup table.",
     {9235, 35160, 8930, 25, 220, 20, 16, 13, 17, 18295, 32439, 23, 18054,
      1898, 13}},
    {"a", {64}},
    {"ab", {365}},
    {"  leading and trailing  ", {220, 6187, 321, 26849, 256}},
    {"multi\nline\ttext with  double  spaces",
     {25429, 198, 1021, 14974, 440, 220, 1923, 220, 12258}},
    {"caf\303\251 na\303\257ve r\303\251sum\303\251",
     {895, 56868, 91603, 571, 238976}},  // café naïve résumé
    {"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
     {42638, 42638, 42638, 42638, 42638, 42638, 4010}},
    {"https://github.com/thomas-hiddenpeak/qwen4-thor",
     {2349, 1074, 5039, 877, 19816, 21576, 12921, 22082, 32773, 16451, 19,
      7324, 269}},
    {"\xe6\x95\xb0\xe5\xad\x97 12345 \xe6\xb7\xb7\xe5\x90\x88 abc ABC 123",
     {99129, 220, 16, 17, 18, 19, 20, 220, 101742, 37730, 18773, 220, 16, 17,
      18}},  // 数字 12345 混合 abc ABC 123
    {"emoji test \xf0\x9f\x9a\x80\xf0\x9f\x8e\x89 done",
     {36280, 1228, 10838, 248, 222, 9008, 236, 231, 2725}},  // 🚀🎉
    {"It's a test: don't, isn't, we're, you've, I'm, they'll, I'd",
     {2064, 579, 264, 1228, 25, 1459, 914, 11, 4290, 914, 11, 567, 2224, 11,
      488, 2908, 11, 353, 2688, 11, 781, 3172, 11, 353, 4035}},
};

}  // namespace

Q4T_TEST(tokenizer_load_real) {
  if (!FileExists(kRealTokenizer)) {
    std::printf("  (skipped: real tokenizer.json not present)\n");
    return true;
  }
  std::unique_ptr<Tokenizer> tok;
  auto s = Tokenizer::Load(kRealTokenizer, TokenizerLimits{}, &tok);
  Q4T_CHECK(s.ok());
  Q4T_CHECK(tok != nullptr);
  Q4T_CHECK(tok->BaseVocabSize() == 248044);
  Q4T_CHECK(tok->MergeCount() == 247587);
  Q4T_CHECK(tok->AddedTokenCount() == 33);
  Q4T_CHECK(tok->VocabSize() == 248044 + 33);
  return true;
}

Q4T_TEST(tokenizer_golden_encode) {
  if (!FileExists(kRealTokenizer)) {
    std::printf("  (skipped: real tokenizer.json not present)\n");
    return true;
  }
  std::unique_ptr<Tokenizer> tok;
  auto s = Tokenizer::Load(kRealTokenizer, TokenizerLimits{}, &tok);
  Q4T_CHECK(s.ok());
  for (const auto& c : kGoldenCases) {
    std::vector<std::uint32_t> ids;
    auto es = tok->Encode(c.text, &ids);
    Q4T_CHECK(es.ok());
    if (ids != c.ids) {
      std::printf("  MISMATCH for %.*s\n    expected ",
                  (int)std::string(c.text).size(), c.text);
      for (auto id : c.ids) std::printf("%u ", id);
      std::printf("\n    got      ");
      for (auto id : ids) std::printf("%u ", id);
      std::printf("\n");
      return false;
    }
  }
  return true;
}

Q4T_TEST(tokenizer_roundtrip_real) {
  if (!FileExists(kRealTokenizer)) {
    std::printf("  (skipped: real tokenizer.json not present)\n");
    return true;
  }
  std::unique_ptr<Tokenizer> tok;
  auto s = Tokenizer::Load(kRealTokenizer, TokenizerLimits{}, &tok);
  Q4T_CHECK(s.ok());
  for (const auto& c : kGoldenCases) {
    std::string decoded;
    auto ds = tok->Decode(c.ids, false, &decoded);
    Q4T_CHECK(ds.ok());
    if (decoded != c.text) {
      std::printf("  ROUNDTRIP MISMATCH\n    text    %.*s\n    decoded %s\n",
                  (int)std::string(c.text).size(), c.text, decoded.c_str());
      return false;
    }
  }
  return true;
}

Q4T_TEST(tokenizer_special_tokens) {
  if (!FileExists(kRealTokenizer)) {
    std::printf("  (skipped: real tokenizer.json not present)\n");
    return true;
  }
  std::unique_ptr<Tokenizer> tok;
  auto s = Tokenizer::Load(kRealTokenizer, TokenizerLimits{}, &tok);
  Q4T_CHECK(s.ok());
  // The real added-token contents (ids 248044+) are the standard Qwen markers
  // (ASCII, written as hex escapes so the source is unambiguous):
  //   248044 =  (eos)
  //   248045 =  (start)
  //   248046 =  (end)
  //   248047 =
  //   248059 =  (tool-call end, non-special)
  // Encoding matches added tokens as whole substrings (like transformers).
  const std::string kStart =
      "\x3c\x7c\x69\x6d\x5f\x73\x74\x61\x72\x74\x7c\x3e";  //
  const std::string kEnd = "\x3c\x7c\x69\x6d\x5f\x65\x6e\x64\x7c\x3e";  //
  const std::string kEos =
      "\x3c\x7c\x65\x6e\x64\x6f\x66\x74\x65\x78\x74\x7c\x3e";  //
  const std::string kObjRef =
      "\x3c\x7c\x6f\x62\x6a\x65\x63\x74\x5f\x72\x65\x66\x5f\x73\x74\x61\x72\x74\x7c\x3e";
  const std::string kToolEnd =
      "\x3c\x2f\x74\x6f\x6f\x6c\x5f\x63\x61\x6c\x6c\x3e";  //

  std::vector<std::uint32_t> ids;
  auto es = tok->Encode(kStart + "\nhello\n" + kEnd, &ids);
  Q4T_CHECK(es.ok());
  const std::vector<std::uint32_t> expected = {248045, 198, 14556, 198,
                                               248046};
  Q4T_CHECK(ids == expected);
  // A marker embedded in normal text is still matched as a whole token.
  auto es2 = tok->Encode("hello " + kStart + " world", &ids);
  Q4T_CHECK(es2.ok());
  const std::vector<std::uint32_t> expected2 = {14556, 220, 248045, 1814};
  Q4T_CHECK(ids == expected2);
  // Decoding added-token ids yields their content (transformers behavior).
  std::string decoded;
  auto ds = tok->Decode({248044, 248045, 248046, 248047}, false, &decoded);
  Q4T_CHECK(ds.ok());
  Q4T_CHECK(decoded == kEos + kStart + kEnd + kObjRef);
  // skip_special_tokens drops the special markers but keeps non-special ones.
  auto ds2 = tok->Decode({248044, 248045, 248059}, true, &decoded);
  Q4T_CHECK(ds2.ok());
  Q4T_CHECK(decoded == kToolEnd);
  return true;
}
