// Differential test: C++ image processor vs the real transformers 5.16.1
// Qwen2VLImageProcessorPil (PIL backend) ground truth.
//
// Two synthetic images are pre-generated by tools/vision_processor_ref.py
// (run with the refenv python that has transformers + PIL):
//   - vision_test_a.png  (256x256, 32-multiple, == min_pixels) -> identity
//     resize. The C++ decode + normalize + patchify must match the processor
//     BIT-FOR-BIT (max_abs_diff == 0). This is the strongest correctness check
//     (it isolates the discrete pipeline from interpolation).
//   - vision_test_b.png  (140x100, not 32-multiple) -> real BICUBIC resize.
//     The C++ Pillow-fixed-point resize must match closely (l2_rel < 0.001).
//
// Ground truth (pixel_values + grid_thw) is saved to vision_proc_gt_{a,b}.json.
// Skipped when the reference files are absent.
#include "q4t/test.h"
#include "q4t/vision/processor.h"

#include <cmath>
#include <cstdint>
#include <cstdio>
#include <cstring>
#include <fcntl.h>
#include <sstream>
#include <string>
#include <unistd.h>
#include <vector>

namespace {

using q4t::vision::ProcessImage;
using q4t::vision::ProcessorConfig;
using q4t::vision::ProcessedImage;

const char* kDir = "/home/rm01/models/dev/qwen4-thor/tools";

bool FileExists(const char* path) {
  int fd = open(path, O_RDONLY);
  if (fd < 0) return false;
  close(fd);
  return true;
}

std::vector<uint8_t> ReadFile(const char* path) {
  std::vector<uint8_t> data;
  FILE* f = fopen(path, "rb");
  if (!f) return data;
  fseek(f, 0, SEEK_END);
  long sz = ftell(f);
  fseek(f, 0, SEEK_SET);
  if (sz <= 0) {
    fclose(f);
    return data;
  }
  data.resize(static_cast<size_t>(sz));
  if (fread(data.data(), 1, data.size(), f) != data.size()) data.clear();
  fclose(f);
  return data;
}

// Parse the plain-text ground truth:
//   line 1: grid_t grid_h grid_w L patch_dim
//   line 2..: flat pixel_values (L * patch_dim floats), space-separated
// Returns false on parse failure or size mismatch.
bool ParseGroundTruth(const std::string& content, int* grid_t, int* grid_h,
                      int* grid_w, int* L, int* patch_dim,
                      std::vector<float>* out) {
  std::istringstream iss(content);
  int gt, gh, gw, l, pd;
  if (!(iss >> gt >> gh >> gw >> l >> pd)) return false;
  *grid_t = gt;
  *grid_h = gh;
  *grid_w = gw;
  *L = l;
  *patch_dim = pd;
  const size_t expected = static_cast<size_t>(l) * pd;
  out->clear();
  out->reserve(expected);
  double v;
  while (iss >> v) {
    out->push_back(static_cast<float>(v));
  }
  return out->size() == expected;
}

// Run the C++ processor on a PNG and compare against the ground truth.
// Returns true on success.
bool CheckImage(const char* name, bool identity) {
  const std::string png_path = std::string(kDir) + "/vision_test_" + name + ".png";
  const std::string gt_path =
      std::string(kDir) + "/vision_proc_gt_" + name + ".txt";
  if (!FileExists(png_path.c_str()) || !FileExists(gt_path.c_str())) {
    std::printf("  [%s] skipped: reference files absent\n", name);
    return true;
  }
  std::vector<uint8_t> png = ReadFile(png_path.c_str());
  std::vector<uint8_t> gt = ReadFile(gt_path.c_str());
  std::string content(gt.begin(), gt.end());

  int gt_t = 0, gt_h = 0, gt_w = 0, gt_L = 0, gt_pd = 0;
  std::vector<float> gt_pv;
  if (!ParseGroundTruth(content, &gt_t, &gt_h, &gt_w, &gt_L, &gt_pd, &gt_pv)) {
    std::printf("  [%s] parse ground truth failed\n", name);
    return false;
  }

  ProcessorConfig cfg;  // defaults match the model's preprocessor_config.json
  ProcessedImage out;
  std::string err;
  if (!ProcessImage(png.data(), png.size(), cfg, &out, &err)) {
    std::printf("  [%s] ProcessImage failed: %s\n", name, err.c_str());
    return false;
  }

  // grid check.
  if (out.grid_h != gt_h || out.grid_w != gt_w || out.grid_t != gt_t) {
    std::printf("  [%s] grid mismatch: got [%d,%d,%d] want [%d,%d,%d]\n", name,
                out.grid_t, out.grid_h, out.grid_w, gt_t, gt_h, gt_w);
    return false;
  }

  // pixel_values check.
  if (out.pixel_values.size() != gt_pv.size()) {
    std::printf("  [%s] size mismatch: got %zu want %zu\n", name,
                out.pixel_values.size(), gt_pv.size());
    return false;
  }
  double max_abs = 0.0, sum_sq = 0.0, ref_sq = 0.0;
  for (size_t i = 0; i < out.pixel_values.size(); ++i) {
    double d = std::fabs(static_cast<double>(out.pixel_values[i]) -
                         static_cast<double>(gt_pv[i]));
    max_abs = std::max(max_abs, d);
    sum_sq += d * d;
    ref_sq += static_cast<double>(gt_pv[i]) * gt_pv[i];
  }
  double l2_rel = ref_sq > 0 ? std::sqrt(sum_sq / ref_sq) : 0.0;
  std::printf("  [%s] grid=[%d,%d,%d] L=%d max_abs_diff=%.9f l2_rel=%.6f%s\n",
              name, out.grid_t, out.grid_h, out.grid_w, out.L(), max_abs,
              l2_rel, identity ? " (identity)" : " (bicubic)");

  if (identity) {
    // Identity resize: must be bit-for-bit (decode + normalize + patchify).
    if (max_abs > 1e-6) {
      std::printf("  [%s] FAIL: identity max_abs_diff=%.9f > 1e-6\n", name,
                  max_abs);
      return false;
    }
  } else {
    // Bicubic: the fixed-point replication should be very close. Allow a
    // small tolerance for float32 rounding in the normalize step.
    if (l2_rel > 0.001) {
      std::printf("  [%s] FAIL: bicubic l2_rel=%.6f > 0.001\n", name, l2_rel);
      return false;
    }
  }
  return true;
}

}  // namespace

Q4T_TEST(vision_processor) {
  bool ok_a = CheckImage("a", /*identity=*/true);
  bool ok_b = CheckImage("b", /*identity=*/false);
  return ok_a && ok_b;
}
