# Close the already-loaded bounded arithmetic review; do not reread large inputs.
terminal=json.loads((R/'result-terminal-review.json').read_bytes())
assert terminal['passed'] is True
owner=json.loads((R/'retention-analysis-01-exit.json').read_bytes())
assert owner['returncode']==0 and owner['failure'] is None and owner['cleanup_complete']
assert owner['started_t']<=analysis['started_t']<=analysis['ended_t']<=owner['ended_t']
sources=dict(terminal['source_sha256'])
for path,record in read_records.items():
    st=Path(path).stat();assert [st.st_dev,st.st_ino,st.st_size,st.st_mtime_ns]==record['stat']
    sources[path]=record['sha256']
for name in ('result-terminal-review.json','result-arithmetic-independent-summary.json','result-projection-review.json','retention-summary.json','build_retention_summary.py','result-reviewer-method-note.json','independent_recompute_retention.py','independent_check_retention_projection.py','seal_independent_retention_review.py'):
    sources[str(R/name)]=hashlib.sha256((R/name).read_bytes()).hexdigest()
limits=[
 'At k1, [10,845] is a conservative interval for the net S-minus-L accumulated entry-candidate count on aligned common GPU misses. The positive lower bound excludes an explanation consisting entirely of contemporaneous exclusive-miss composition. It does not attribute all470 observed candidates to retention or identify which ten events account for the bound.',
 'The upper bound845 may exceed the total candidate difference470 because exclusive-miss contributions may be negative. Independent per-plan partition caps and summed layer intervals are outer relaxations, not a claim that every value is jointly achievable or a percentage decomposition of470.',
 'Input identity is equality of SHA-bound token sidecars, and route identity is ordered top10 expert IDs. This is controlled recorded demand; it is not a claim about all router weights, hidden activations, numerical equivalence of arbitrary model executions or independent repeated services.',
 'All k0..k3 and48 layers remain included. k0 has different inputs and routes; k2[-447,214] and k3[-188,111] include zero. Old sixteen requests are not pooled, and the eight requests/positions are not independent repetitions.',
 'Possible mirror support includes captured decode-entry IDs plus all strictly earlier occupied GPU victims. It can exceed eight IDs and does not assert actual residency; it is never trimmed to the last eight victims. Capacity23310 versus observed candidates4482 is not avoidable READ work or a candidate savings ceiling.',
 'Victim distances exclude entire source and demand plans, count strictly intervening occupied victim events and provide no within-plan ordering or wall-clock lifetime. The k1 counts987/501 for0..7 intervening victims describe potential reuse opportunities; their486 difference is not an identified cause of the470 candidate difference.',
 'Captured endpoint GPU-covered copies S2/L6 and sole copies S382/L378 establish mixed occupancy only. They do not establish an available safe alternative at any actual reservation, continued GPU coverage, mirror survival until a future miss, overwrite causality or realizable benefit. Repeated boundary snapshots are not independent samples or physical RAM measurements.',
 'The frozen gate nominates exactly one future GPU-covered-mirror recycling rule for consideration. No runtime policy was implemented or admitted; no additional observer is triggered. Any implementation needs current thread-safe state, original claim/in-flight/event protection and fallback, with a separate default-off HTTP-first acceptance stage.',
 'This independent review did not reparse route payloads or raw resources and did not repeat GPU state replay. Exact GPU endpoints/EOF proof is reused from the SHA-bound successful runner and passed same-source45 contracts, while all projected missing/victim arithmetic, observed prefix counters, endpoint memberships and common intervals were recomputed independently.',
 'The three current inputs/plans/analysis artifacts were each content-read and SHA-checked once, then retained in one reviewer session. Their stat signatures were rechecked at sealing. The old observer proof and its transitive raw evidence were not recursively reopened; finite local receipts/source identity were checked separately.',
 'Project extraction,45 host contracts and actual eight-trace analysis passed on their first recorded runs. The independent auxiliary comparison did not pass on its first attempt: Python Counter addition dropped zero-valued keys. That reviewer-only mistake and corrected method are retained; no project test/data/trace rerun or artifact reread occurred.',
 'Prior performance NO_GO/default-off, GEMM/precision/budget/MTP/Phase-D constraints and physical RAM54GB INDETERMINATE remain. No new model/HTTP/resource measurement, latency claim, physical I/O claim or global cleanliness proof is supplied by this review. Final MAIN/old-worktree protection and delivery still require their own closure.'
]
result={'schema':1,'passed':True,'independent_review':True,'reviewer':'/root/supply_observer_review','scope_sha256':analysis['scope_sha256'],'execution_plan_sha256':analysis['execution_plan_sha256'],'manifest_sha256':expected['retention-inputs.json'],'analysis_sha256':expected['retention-analysis.json'],'plans_sha256':expected['decode-plans.json'],'runner_source_commit':execution['runner_source_commit'],'runtime_source_commit':inp['runtime_source_commit'],'runtime_binary_sha256':inp['runtime_binary_sha256'],
 'blocking_findings':[],'scope':{'requests':8,'layers':48,'true_decode_forwards_per_request':255,'new_host_contracts':45,'core_contracts':26,'runner_contracts':19,'actual_project_trace_passes':1,'owned_terminals':3,'new_HTTP':0,'model_runs':0,'runtime_changes':False},
 'independent_checks':review_compact['checks'],'entry_mirror_first_event_records_recomputed':3072,'reviewer_artifact_reads':read_records,'new_route_parses_by_reviewer':0,'new_GPU_replays_by_reviewer':0,'raw_resource_reads_by_reviewer':0,'model_payload_reads_by_reviewer':0,
 'independent_review_first_attempt_passed':False,'reviewer_method_correction':{'path':str(R/'result-reviewer-method-note.json'),'sha256':sources[str(R/'result-reviewer-method-note.json')],'kind':'auxiliary_zero_key_aggregation','project_execution_failure':False,'artifacts_reread':False,'trace_reparsed':False},
 'observations':{'GPU_misses':54825,'potential_supported_miss_occurrences':23316,'sum_per_plan_potential_capacity':23310,'observed_entry_candidate_occurrences':4482,'primary':{'position':1,'same_input_tokens':True,'same_input_length':True,'ordered_route_IDs_equal':True,'common_GPU_misses':6529,'S_only_GPU_misses':471,'L_only_GPU_misses':698,'observed_candidates_S':950,'observed_candidates_L':480,'candidate_difference_S_minus_L':470,'supported_exclusive_capacity_S':460,'supported_exclusive_capacity_L':576,'total_potential_capacity_S':3198,'total_potential_capacity_L':3371,'common_difference_interval':{'lower':10,'upper':845},'decode_entry_GPU_covered_S':2,'decode_entry_GPU_covered_L':6,'decode_entry_sole_S':382,'decode_entry_sole_L':378,'potential_misses_with_0_to_7_strictly_intervening_victims_S':987,'potential_misses_with_0_to_7_strictly_intervening_victims_L':501},'all_positions_intervals':[{k:c[k] for k in ('position','same_input_length','same_input_tokens','route_equal','common_candidate_difference_interval')} for c in review_compact['comparisons']]},
 'gate_assessment':{'decision':analysis['decision'],'all_frozen_requirements_met':True,'input_length_and_SHA_match':True,'ordered_route_match':True,'primary_common_lower_bound_positive':True,'primary_decode_entry_same_layer_GPUcovered_and_sole_mixed':True,'future_candidate_count':1,'hypothesis_identified':False,'runtime_candidate_admitted':False,'automatic_new_observer':False},
 'projection_review':{'path':str(R/'retention-summary.json'),'sha256':projection_sha,'all_fields_verified':True,'requests':8,'endpoints':24,'layer_intervals':192},
 'draft_fact_boundary_review':{'path':str(R/'final-report-draft.md'),'reviewed_sha256':hashlib.sha256((R/'final-report-draft.md').read_bytes()).hexdigest(),'passed_for_current_quantitative_claims_and_limits':True,'final_protection_and_delivery_text_pending':True,'independent_method_correction_must_be_retained':True},
 'limits':limits,'source_sha256':sources,'recorded_t':time.time()}
assert result['recorded_t']>owner['ended_t']
path=R/'result-independent-review.json'
with path.open('x') as f:json.dump(result,f,indent=2,allow_nan=False);f.write('\n')
print('FINAL_REVIEW_SHA',hashlib.sha256(path.read_bytes()).hexdigest(),'source_bindings',len(sources),'bytes',path.stat().st_size)
